### ISSUE TITLE
[suggestion] change upload-interval

### ISSUE THREAD

**Issue by fritsvp** [omoerbeek/e2pv#6]
new data is now sent each 540 seconds (9 minutes).
pv output converts it to each ten minutes (HH:M0)
i suggest to rewrite the '540' line to something that will trigger when:
* $last is over 5 minutes ago
* current time (%M) modulo 10 < 5.

I now got this replacement:

      $min = idate('i') % 10;
    [..]
    //  } elseif ($last < $time - 540) {
      } elseif ($last < $time - 300 && $min < 5 ) {

**Comment by omoerbeek** [comment]
On Sun, Jun 21, 2015 at 12:32:34PM -0700, fritsvp wrote:

> new data is now sent each 540 seconds (9 minutes).
> pv output converts it to each ten minutes (HH:M0)
> i suggest to rewrite the '540' line to something that will trigger when:
> * $last is over 5 minutes ago
> * current time (%M) modulo 10 < 5.
> 
> I now got this replacement:
> 
>       $min = idate('i') % 10;
>     [..]
>     //  } elseif ($last < $time - 540) {
>       } elseif ($last < $time - 300 && $min < 5 ) {
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/omoerbeek/e2pv/issues/6

I'll think about it. Originally, the 9 minutes was to ensure at least
one sample is sent every 10 min. Since the data is coming in at 1
mint inetervals, it could happen that an 10m interval was was missed.

But it's indeed probably better to send close the 10 min boundary.

	-Otto

**Comment by omoerbeek** [comment]
Included your suggestion in the master branch, thanks.
